### ISSUE TITLE
Proxy support for outgoing requests

### ISSUE THREAD

**Issue by ktk** [zazuko/sparql-proxy#9]
In intranet scenarios where the SPARQL endpoint is external one needs support for proxy within the SPARQL proxy itself. So an outgoing SPARQL query would have to go via the proxy configured in the system. Typically this is done by env-vars like `HTTP_PROXY` and `HTTPS_PROXY`.

We need a way to support that for the SPARQL proxy directly from node, which seems to be an ongoing question within the node.js community. Most recently @bergos pointed to this: https://github.com/nodejs/node/issues/8381#issuecomment-486717645

We should check what makes sense and add optional support for proxies. Ideally it would simply use the proxy when the env-variables are set, like `curl` does.

**Comment by vhf** [comment]
I think you'd have to pass an agent: https://github.com/zazuko/sparql-proxy/issues/1

I'm not sure adding proxy support to this package makes sense though?

**Comment by ludovicm67** [comment]
This issue is open for a too long time : I will close it.
If this is still something that is needed, please create a new issue.
